#ifndef __CIRC_LATTICE_PARAMS__
#define __CIRC_LATTICE_PARAMS__

// BEWARE: GENERATED BY SCRIPT

#include "lwe/lwe_params.hpp"
#include "lwe/container/utils.hpp"

namespace LWE {

    class B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = (1 << 13) - 1;
    };

    class B13FpParamsBase {
    public:
        static constexpr const uint32_t tau = 10;
        static constexpr const uint64_t p_int = (1 << 13) - 1;
    };

    class B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t tau = 4;
        static constexpr const uint64_t p_int = (1 << 19) - 1;
    };

    class B19FpParamsBase {
    public:
        static constexpr const uint32_t tau = 7;
        static constexpr const uint64_t p_int = (1 << 19) - 1;
    };

    class B23FpParamsBase {
    public:
        static constexpr const uint32_t tau = 6;
        static constexpr const uint64_t p_int = 7 * (1 << 20) + 1;
    };

    class B28FpParamsBase {
    public:
        static constexpr const uint32_t tau = 5;
        static constexpr const uint64_t p_int = 5 * (1 << 25) + 1;
    };

    class B13C10 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1720;
        static constexpr const uint64_t q_log = 88;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 4011379454;
        static constexpr const uint32_t query_num = 9;
        static constexpr const uint128_t b_int = 10929659834875890368512_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 10.0;
    };

    class B13C11 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1725;
        static constexpr const uint64_t q_log = 89;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 4511604848;
        static constexpr const uint32_t query_num = 10;
        static constexpr const uint128_t b_int = 20743838125039055536128_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 12.0;
    };

    class B13C12 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1735;
        static constexpr const uint64_t q_log = 90;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 5721540461;
        static constexpr const uint32_t query_num = 10;
        static constexpr const uint128_t b_int = 39529219829337686016000_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 16.0;
    };

    class B13C13 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1740;
        static constexpr const uint64_t q_log = 91;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 7074959869;
        static constexpr const uint32_t query_num = 11;
        static constexpr const uint128_t b_int = 78064457470425534824448_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 20.0;
    };

    class B13C14 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1750;
        static constexpr const uint64_t q_log = 92;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 8780842103;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 154236921207511167533056_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 25.0;
    };

    class B13C15 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1755;
        static constexpr const uint64_t q_log = 93;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 11320084869;
        static constexpr const uint32_t query_num = 13;
        static constexpr const uint128_t b_int = 309742398573538732670976_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 32.0;
    };

    class B13C16 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1770;
        static constexpr const uint64_t q_log = 94;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 12706174084;
        static constexpr const uint32_t query_num = 15;
        static constexpr const uint128_t b_int = 613092451834003078512640_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 36.0;
    };

    class B13C17 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1775;
        static constexpr const uint64_t q_log = 95;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 15793894407;
        static constexpr const uint32_t query_num = 16;
        static constexpr const uint128_t b_int = 1216095626339802989723648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 45.0;
    };

    class B13C18 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1785;
        static constexpr const uint64_t q_log = 96;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 19607312765;
        static constexpr const uint32_t query_num = 19;
        static constexpr const uint128_t b_int = 2585918839680265831317504_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 52.0;
    };

    class B13C19 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1800;
        static constexpr const uint64_t q_log = 97;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 23121448381;
        static constexpr const uint32_t query_num = 22;
        static constexpr const uint128_t b_int = 5379727647926364139421696_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 58.0;
    };

    class B13C20 : public B13Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1815;
        static constexpr const uint64_t q_log = 98;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 28442379382;
        static constexpr const uint32_t query_num = 26;
        static constexpr const uint128_t b_int = 11579451727134268130852864_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 64.0;
    };

    class B13C10E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3400;
        static constexpr const uint64_t q_log = 87;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 5460620763;
        static constexpr const uint32_t query_num = 9;
        static constexpr const uint128_t b_int = 6555404714703381856256_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 10.0;
    };

    class B13C11E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3410;
        static constexpr const uint64_t q_log = 88;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 5594478597;
        static constexpr const uint32_t query_num = 10;
        static constexpr const uint128_t b_int = 12100689111355452555264_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 12.0;
    };

    class B13C12E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3420;
        static constexpr const uint64_t q_log = 89;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 6798704059;
        static constexpr const uint32_t query_num = 10;
        static constexpr const uint128_t b_int = 22837978890377153740800_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 16.0;
    };

    class B13C13E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3435;
        static constexpr const uint64_t q_log = 90;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 8158002557;
        static constexpr const uint32_t query_num = 11;
        static constexpr const uint128_t b_int = 44292257178121062580224_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 20.0;
    };

    class B13C14E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3450;
        static constexpr const uint64_t q_log = 91;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 9840823030;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 86034400393391167766528_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 25.0;
    };

    class B13C15E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3460;
        static constexpr const uint64_t q_log = 92;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 12494469492;
        static constexpr const uint32_t query_num = 13;
        static constexpr const uint128_t b_int = 170627763159065425870848_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 32.0;
    };

    class B13C16E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3480;
        static constexpr const uint64_t q_log = 93;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 16548899820;
        static constexpr const uint32_t query_num = 15;
        static constexpr const uint128_t b_int = 354627891213956714332160_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 40.0;
    };

    class B13C17E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3500;
        static constexpr const uint64_t q_log = 94;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 18624638471;
        static constexpr const uint32_t query_num = 16;
        static constexpr const uint128_t b_int = 673075782013208445845504_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 48.0;
    };

    class B13C18E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3525;
        static constexpr const uint64_t q_log = 95;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 21807448113;
        static constexpr const uint32_t query_num = 19;
        static constexpr const uint128_t b_int = 1380811084924322303705088_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 54.0;
    };

    class B13C19E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3555;
        static constexpr const uint64_t q_log = 96;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 25122542413;
        static constexpr const uint32_t query_num = 22;
        static constexpr const uint128_t b_int = 2818259506972953306726400_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 60.0;
    };

    class B13C20E : public B13FpParamsBase {
    public:
        static constexpr const uint32_t n = 3585;
        static constexpr const uint64_t q_log = 97;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 30453499166;
        static constexpr const uint32_t query_num = 26;
        static constexpr const uint128_t b_int = 5979181420671654732759040_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 66.0;
    };

    class B19C10 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1950;
        static constexpr const uint64_t q_log = 98;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 365561207906;
        static constexpr const uint32_t query_num = 5;
        static constexpr const uint128_t b_int = 241373738930047291490304_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 6.0;
    };

    class B19C11 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1965;
        static constexpr const uint64_t q_log = 99;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 313817751023;
        static constexpr const uint32_t query_num = 5;
        static constexpr const uint128_t b_int = 437775200558470270025728_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 7.0;
    };

    class B19C12 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1970;
        static constexpr const uint64_t q_log = 100;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 424726471593;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 926699948730902437167104_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 8.0;
    };

    class B19C13 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1980;
        static constexpr const uint64_t q_log = 101;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 458399328487;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 1760797942768951067934720_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 10.0;
    };

    class B19C14 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 1990;
        static constexpr const uint64_t q_log = 102;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 475619535066;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 3308191006253048806768640_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 12.0;
    };

    class B19C15 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2000;
        static constexpr const uint64_t q_log = 103;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 547764047829;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 6338925132362660597202944_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 15.0;
    };

    class B19C16 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2005;
        static constexpr const uint64_t q_log = 104;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 786419490485;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 13758087633029525005139968_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };

    class B19C17 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2015;
        static constexpr const uint64_t q_log = 105;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 878574989848;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 26405072246455438466351104_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 22.0;
    };

    class B19C18 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2030;
        static constexpr const uint64_t q_log = 106;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 903607597974;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 50032066751862035099680768_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 25.0;
    };

    class B19C19 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2040;
        static constexpr const uint64_t q_log = 107;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 1294092887613;
        static constexpr const uint32_t query_num = 8;
        static constexpr const uint128_t b_int = 108701510150508083664650240_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 30.0;
    };

    class B19C20 : public B19Fp2ParamsBase {
    public:
        static constexpr const uint32_t n = 2045;
        static constexpr const uint64_t q_log = 108;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 1684330191549;
        static constexpr const uint32_t query_num = 8;
        static constexpr const uint128_t b_int = 214923454510919237360418816_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 40.0;
    };

    class B19C10E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3855;
        static constexpr const uint64_t q_log = 97;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 336370480603;
        static constexpr const uint32_t query_num = 5;
        static constexpr const uint128_t b_int = 118427728537655179214848_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 6.0;
    };

    class B19C11E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3880;
        static constexpr const uint64_t q_log = 98;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 294924020396;
        static constexpr const uint32_t query_num = 5;
        static constexpr const uint128_t b_int = 214676578267520963706880_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 7.0;
    };

    class B19C12E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3895;
        static constexpr const uint64_t q_log = 99;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 398049176156;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 455612288617220208066560_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 8.0;
    };

    class B19C13E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3910;
        static constexpr const uint64_t q_log = 100;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 432998671879;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 865517895928057983664128_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 10.0;
    };

    class B19C14E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3930;
        static constexpr const uint64_t q_log = 101;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 452851847740;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 1625774435318445060915200_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 12.0;
    };

    class B19C15E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3950;
        static constexpr const uint64_t q_log = 102;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 523727585899;
        static constexpr const uint32_t query_num = 6;
        static constexpr const uint128_t b_int = 3114775366834343135674368_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 15.0;
    };

    class B19C16E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3970;
        static constexpr const uint64_t q_log = 103;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 750538336523;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 6774734025252574580441088_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 18.0;
    };

    class B19C17E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 3990;
        static constexpr const uint64_t q_log = 104;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 842213588738;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 13001013937378686624858112_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 22.0;
    };

    class B19C18E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 4010;
        static constexpr const uint64_t q_log = 105;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 1021079342170;
        static constexpr const uint32_t query_num = 7;
        static constexpr const uint128_t b_int = 25303903821867235053404160_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 28.0;
    };

    class B19C19E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 4030;
        static constexpr const uint64_t q_log = 106;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 1238174007006;
        static constexpr const uint32_t query_num = 8;
        static constexpr const uint128_t b_int = 53605950156849797746655232_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 30.0;
    };

    class B19C20E : public B19FpParamsBase {
    public:
        static constexpr const uint32_t n = 4050;
        static constexpr const uint64_t q_log = 107;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 1397802099083;
        static constexpr const uint32_t query_num = 8;
        static constexpr const uint128_t b_int = 103968589987727417163120640_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size * 2;
        static constexpr const double width = 36.0;
    };

    class B23C10 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4035;
        static constexpr const uint64_t q_log = 106;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 16260489971809;
        static constexpr const uint32_t query_num = 11;
        static constexpr const uint128_t b_int = 3714624018668462687649792_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 30.0;
    };

    class B23C11 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4055;
        static constexpr const uint64_t q_log = 107;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 17274887298823;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 6939553050986080993542144_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 36.0;
    };

    class B23C12 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4080;
        static constexpr const uint64_t q_log = 108;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 17354242588381;
        static constexpr const uint32_t query_num = 14;
        static constexpr const uint128_t b_int = 12950702190635345900470272_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 40.0;
    };

    class B23C13 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4100;
        static constexpr const uint64_t q_log = 109;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 19004036831249;
        static constexpr const uint32_t query_num = 15;
        static constexpr const uint128_t b_int = 24048426034953107923795968_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 48.0;
    };

    class B23C14 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4120;
        static constexpr const uint64_t q_log = 110;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 22731593281083;
        static constexpr const uint32_t query_num = 17;
        static constexpr const uint128_t b_int = 47487234983520684103172096_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 58.0;
    };

    class B23C15 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4145;
        static constexpr const uint64_t q_log = 111;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 25550638577489;
        static constexpr const uint32_t query_num = 19;
        static constexpr const uint128_t b_int = 90930816994537941621538816_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 68.0;
    };

    class B23C16 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4170;
        static constexpr const uint64_t q_log = 112;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 27537275613758;
        static constexpr const uint32_t query_num = 23;
        static constexpr const uint128_t b_int = 179143898397593265393106944_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 74.0;
    };

    class B23C17 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4200;
        static constexpr const uint64_t q_log = 113;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 31481813457101;
        static constexpr const uint32_t query_num = 27;
        static constexpr const uint128_t b_int = 358270103339637731795927040_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 84.0;
    };

    class B23C18 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4230;
        static constexpr const uint64_t q_log = 114;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 36787381028612;
        static constexpr const uint32_t query_num = 35;
        static constexpr const uint128_t b_int = 769988485395913847955521536_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 90.0;
    };

    class B23C19 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4270;
        static constexpr const uint64_t q_log = 115;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 43235454974958;
        static constexpr const uint32_t query_num = 48;
        static constexpr const uint128_t b_int = 1721929958819522260324319232_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 90.0;
    };

    class B23C20 : public B23FpParamsBase {
    public:
        static constexpr const uint32_t n = 4310;
        static constexpr const uint64_t q_log = 116;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 123476787324366;
        static constexpr const uint32_t query_num = 81;
        static constexpr const uint128_t b_int = 4876201205794506211516743680_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 90.0;
    };

    class B28C10 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4470;
        static constexpr const uint64_t q_log = 113;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 121989877110087;
        static constexpr const uint32_t query_num = 8;
        static constexpr const uint128_t b_int = 21816065574297384467300352_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 8.0;
    };

    class B28C11 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4490;
        static constexpr const uint64_t q_log = 114;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 124227341141594;
        static constexpr const uint32_t query_num = 9;
        static constexpr const uint128_t b_int = 41628841244461404608528384_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 9.0;
    };

    class B28C12 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4520;
        static constexpr const uint64_t q_log = 115;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 108861030128265;
        static constexpr const uint32_t query_num = 9;
        static constexpr const uint128_t b_int = 72052565208253734563348480_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 10.0;
    };

    class B28C13 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4540;
        static constexpr const uint64_t q_log = 116;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 131722386072252;
        static constexpr const uint32_t query_num = 10;
        static constexpr const uint128_t b_int = 144506744203303122748047360_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 12.0;
    };

    class B28C14 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4560;
        static constexpr const uint64_t q_log = 117;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 170628347286635;
        static constexpr const uint32_t query_num = 11;
        static constexpr const uint128_t b_int = 295356880317134932587577344_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 15.0;
    };

    class B28C15 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4580;
        static constexpr const uint64_t q_log = 118;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 205634377241378;
        static constexpr const uint32_t query_num = 12;
        static constexpr const uint128_t b_int = 590679829335140766631067648_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 18.0;
    };

    class B28C16 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4600;
        static constexpr const uint64_t q_log = 119;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 219733176826555;
        static constexpr const uint32_t query_num = 13;
        static constexpr const uint128_t b_int = 1145900962115930913517862912_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 20.0;
    };

    class B28C17 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4620;
        static constexpr const uint64_t q_log = 120;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 266860005606056;
        static constexpr const uint32_t query_num = 14;
        static constexpr const uint128_t b_int = 2304527708071391456489635840_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 24.0;
    };

    class B28C18 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4650;
        static constexpr const uint64_t q_log = 121;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 341820871283024;
        static constexpr const uint32_t query_num = 16;
        static constexpr const uint128_t b_int = 4884983511890910183444971520_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 28.0;
    };

    class B28C19 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4670;
        static constexpr const uint64_t q_log = 122;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 425201647001945;
        static constexpr const uint32_t query_num = 18;
        static constexpr const uint128_t b_int = 10239630903257711370706092032_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 32.0;
    };

    class B28C20 : public B28FpParamsBase {
    public:
        static constexpr const uint32_t n = 4700;
        static constexpr const uint64_t q_log = 123;
        static constexpr const uint128_t q_int = (uint128_t) 1 << q_log;
        static constexpr const uint128_t rescale_q = 529594233132359;
        static constexpr const uint32_t query_num = 21;
        static constexpr const uint128_t b_int = 22065288519192952863365005312_U128T;
        static constexpr const uint32_t pt_dim = query_num * query_size;
        static constexpr const double width = 34.0;
    };

}

#endif
